
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtvkmzlvanzvnyxgzbhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0dmttemx2YW56dm55eGd6YmhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyODkxNTksImV4cCI6MjA1ODg2NTE1OX0.AOtoQcUe4W3YRMYd3wUJ_ytfuw59s8oaBxuIIx_eidY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
